spring:
  application:
    name: mserver-transaccion-mongodb

  data:
    mongodb:
      uri: mongodb://localhost:27017/transacciones_db

server:
  port: 8989

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7575/eureka/
