spring:
  application:
    name: mserver-transaccion-mysql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bdtransaccion
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8787

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7575/eureka/
